{% set version = "1.0" %}

package:
  name: caffe
  version: {{ version }}

source:
  url: https://github.com/BVLC/caffe/archive/{{ version }}.tar.gz
  sha256: 71d3c9eb8a183150f965a465824d01fe82826c22505f7aa314f700ace03fa77f
  patches:
    - backport_6638-support-opencv4.patch

build:
  number: 204
  detect_binary_files_with_prefix: False
  skip: True  # [win or osx or blas_impl != 'openblas']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost
    - cython
    # Unpin hdf5 when the new h5py is released.
    - hdf5 1.10.4
    - gflags
    - glog
    - h5py
    - ipython
    - leveldb
    - protobuf
    - lmdb
    - libcblas      # [blas_impl == 'mkl']
    - mkl-include   # [blas_impl == 'mkl']
    - mkl           # [blas_impl == 'mkl']
    - mkl-devel     # [blas_impl == 'mkl']
    # Some of its dependencies are not built with openblas 0.3.6 yet.
    - openblas      # [blas_impl == 'openblas']
    - matplotlib
    - networkx
    - nose
    - opencv
    - pandas
    - pillow
    - python-dateutil
    - python-gflags
    - python-leveldb
    - pyyaml
    - scikit-image
    - six
    - snappy
    - numpy
  run:
    - python
    - opencv
    - gflags
    - lmdb
    - h5py
    - ipython
    - matplotlib
    - networkx
    - {{ pin_compatible('numpy') }}
    - pandas
    - protobuf
    - python-dateutil
    - python-gflags
    - python-leveldb
    - pyyaml
    - scikit-image
    - scipy
    - six

test:
  commands:
    # Test commands.
    - command -v "${PREFIX}/bin/caffe"                        # [unix]
    - command -v "${PREFIX}/bin/classification"               # [unix]
    - command -v "${PREFIX}/bin/compute_image_mean"           # [unix]
    - command -v "${PREFIX}/bin/convert_cifar_data"           # [unix]
    - command -v "${PREFIX}/bin/convert_imageset"             # [unix]
    - command -v "${PREFIX}/bin/convert_mnist_data"           # [unix]
    - command -v "${PREFIX}/bin/convert_mnist_siamese_data"   # [unix]
    - command -v "${PREFIX}/bin/device_query"                 # [unix]
    - command -v "${PREFIX}/bin/extract_features"             # [unix]
    - command -v "${PREFIX}/bin/finetune_net"                 # [unix]
    - command -v "${PREFIX}/bin/net_speed_benchmark"          # [unix]
    - command -v "${PREFIX}/bin/test_net"                     # [unix]
    - command -v "${PREFIX}/bin/train_net"                    # [unix]
    - command -v "${PREFIX}/bin/upgrade_net_proto_binary"     # [unix]
    - command -v "${PREFIX}/bin/upgrade_net_proto_text"       # [unix]
    - command -v "${PREFIX}/bin/upgrade_solver_proto_text"    # [unix]

    # Test includes.
    - test -d "${PREFIX}/include/caffe"                       # [unix]

    # Test libraries.
    - test -f "${PREFIX}/lib/libcaffe${SHLIB_EXT}"            # [unix]
    - test -f "${PREFIX}/lib/libcaffe.a"                      # [unix]
    

  imports:
    - caffe

about:
  home: http://caffe.berkeleyvision.org/
  license: BSD-2-Clause
  summary: "A deep learning framework made with expression, speed, and modularity in mind"
  description: |
    Caffe is a deep learning framework brewed for expression, speed,modularity, openness and community.
  doc_url: http://caffe.berkeleyvision.org/tutorial/
  doc_source_url: https://github.com/BVLC/caffe

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - marcelotrevisani
    - ocefpaf
