{% set version = "1.0" %}
{% set build = 203 %}


package:
  name: caffe
  version: {{ version }}

source:
  url: https://github.com/BVLC/caffe/archive/{{ version }}.tar.gz
  sha256: 71d3c9eb8a183150f965a465824d01fe82826c22505f7aa314f700ace03fa77f
  patches:
    - remove-py-tests.patch

build:
  number: {{ build }}
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - cython
    - boost
    - hdf5
    - gflags 2.2.*
    - glog
    - h5py
    - ipython
    - leveldb
    - lmdb
    - matplotlib
    - networkx
    - nose
    - numpy
    - opencv <4
    - pandas
    - pillow
    - protobuf
    - python
    - python-dateutil
    - python-gflags
    - python-leveldb
    - pyyaml
    - scikit-image
    - scipy
    - six
    - snappy
    - libblas
    - libcblas
    - gtest

  run:
    - boost
    - hdf5
    - gflags
    - glog
    - h5py
    - ipython
    - leveldb
    - lmdb
    - matplotlib
    - networkx
    - numpy
    - opencv <4
    - pandas
    - pillow
    - protobuf
    - python
    - python-dateutil
    - python-gflags
    - python-leveldb
    - pyyaml
    - scikit-image
    - scipy
    - six
    - snappy

test:
  commands:
    # Test includes.
    - test -d "${PREFIX}/include/caffe"
    - test -d "${PREFIX}/bin/caffe"

    # Test libraries.
    - test -f "${PREFIX}/lib/libcaffe.so"

  imports:
    - caffe

about:
  home: http://caffe.berkeleyvision.org/
  license: BSD 2-Clause
  summary: A deep learning framework made with expression, speed, and modularity in mind.

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - marcelotrevisani
